### ISSUE TITLE
Unable to install on Windows

### ISSUE THREAD

**Issue by 1Map** [FH-Potsdam/shifted-maps#49]
In package.json, you have:

"scripts": {
    ....
    "postinstall": "bower install && node_modules/.bin/gulp browserify compass compress"
  },

This will only work in Linux (&& and /)

I have Windows (Which uses \ and do not recognize the &&)

**Comment by lennerd** [comment]
Thanks for reporting this issue. This definitly need a better way to work on both unix and windows. I also recognized some errors when installing that project on a new system due to missing dependencies.

I will try to look into this. But we are working on our next research paper at the moment and we therefore have less time for the development of the prototype.

Your welcome to create a PR to fix this, thou. :wink:

**Comment by lennerd** [comment]
Sorry for the late message. Just realized that your bug was fixed when I revamped the whole application (new React version, using Next and Typescript 🎉).

You should be able to install the application on your machine. Unfortunately we do not have any data import anymore, because Move canceled their services.

Let me know what you think and if you had any luck installing the application on Windows.
